server:
  port: 8585
logging:
  file: flow.log
  level:
    com:
      checkmarx:
        flow:
          cmd: TRACE
          service: TRACE
          controller: TRACE

cx-flow:
  bug-tracker: Azure
  bug-tracker-impl:
    - Azure
  branches:
    - master
  filter-severity:
  filter-category:
  filter-cwe:
  filter-status:
  codebash-url: https://checkmarx-demo.codebashing.com/courses/
  track-application-only: true


checkmarx:
  username: develop1
  password: General123!
  client-id: resource_owner_client
  scope: access_control_api sast_rest_api
  client-secret: 014DF517-39D1-4453-B7B3-9930C563627C
  base-url: https://ronenlab.ngrok.io
  team: /CxServer/Finanzas
  url: ${checkmarx.base-url}/cxrestapi
  portal-url: ${checkmarx.base-url}/cxwebinterface/Portal/CxWebService.asmx
  sdk-url: ${checkmarx.base-url}/cxwebinterface/SDK/CxSDKWebService.asmx
  portal-wsdl: ${checkmarx.base-url}/Portal/CxWebService.asmx?wsdl
  sdk-wsdl: ${checkmarx.base-url}/SDK/CxSDKWebService.asmx?wsdl
  incremental: true
  version: 9.3
  multi-tenant: false
  configuration: Default Configuration
  scan-preset: Checkmarx Default
  preserve-xml: true

azure:
  webhook-token: cxflow:12345
  token: enwbwvmcupfexs57snttjrtm7niqjrkcawgutuvagavvrlcxzpja
  url: https://dev.azure.com/ronenriesenfeld
  issue-type: issue
  api-version: 5.0
  false-positive-label: false-positive
  block-merge: true
  closed-status: Done
  open-status: "To Do"

  
