#
# Example for a DAST web scan
#
trigger:
  - master
pool:
  vmImage: "ubuntu-latest"
container: checkmarx/dast:latest
steps:
  # DAST should fail the pipeline if results are found
  - script: |
    /app/bin/dast web --config ${PWD}/zap_config.yaml --verbose --environment-id  5296fe9b-c3f1-4968-9f0d-bdce3d69acf7
    env: AST_API_KEY: $(SecretKey)